
package com.jason.demo.service.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.jason.demo.service.ObjectFactory;
import com.jason.demo.service.User;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IMyService", targetNamespace = "http://service.demo.jason.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IMyService {


    /**
     * 
     * @param password
     * @param username
     * @return
     *     returns com.jason.demo.service.User
     */
    @WebMethod
    @WebResult(name = "loginUser", targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://service.demo.jason.com/", className = "com.jason.demo.service.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://service.demo.jason.com/", className = "com.jason.demo.service.LoginResponse")
    @Action(input = "http://service.demo.jason.com/IMyService/loginRequest", output = "http://service.demo.jason.com/IMyService/loginResponse")
    public User login(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password);

}
