package com.jason.demo.CXFClientWSDL;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-04-13T09:55:47.029+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://service.demo.jason.com/", name = "IMyService")
@XmlSeeAlso({ObjectFactory.class})
public interface IMyService {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://service.demo.jason.com/IMyService/helloRequest", output = "http://service.demo.jason.com/IMyService/helloResponse")
    @RequestWrapper(localName = "hello", targetNamespace = "http://service.demo.jason.com/", className = "com.jason.demo.CXFClientWSDL.Hello")
    @WebMethod
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://service.demo.jason.com/", className = "com.jason.demo.CXFClientWSDL.HelloResponse")
    public java.lang.String hello();
}
