package com.jason.demo.CXFClientWSDL;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-04-13T09:55:47.048+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "MyServiceImplService", 
                  wsdlLocation = "file:/F:/My_Training/WebService/demo5_cxf_webservice_spring_maven/src/main/java/com/jason/demo/CXFClientWSDL/jasonws.wsdl",
                  targetNamespace = "http://Impl.service.demo.jason.com/") 
public class MyServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://Impl.service.demo.jason.com/", "MyServiceImplService");
    public final static QName MyServiceImplPort = new QName("http://Impl.service.demo.jason.com/", "MyServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/F:/My_Training/WebService/demo5_cxf_webservice_spring_maven/src/main/java/com/jason/demo/CXFClientWSDL/jasonws.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MyServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/F:/My_Training/WebService/demo5_cxf_webservice_spring_maven/src/main/java/com/jason/demo/CXFClientWSDL/jasonws.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MyServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MyServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MyServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MyServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MyServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IMyService
     */
    @WebEndpoint(name = "MyServiceImplPort")
    public IMyService getMyServiceImplPort() {
        return super.getPort(MyServiceImplPort, IMyService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IMyService
     */
    @WebEndpoint(name = "MyServiceImplPort")
    public IMyService getMyServiceImplPort(WebServiceFeature... features) {
        return super.getPort(MyServiceImplPort, IMyService.class, features);
    }

}
