package com.jason.demo.clientWSDL;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-04-12T16:38:10.747+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://service.demo.jason.com/", name = "IHelloService")
@XmlSeeAlso({ObjectFactory.class})
public interface IHelloService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "bye", targetNamespace = "http://service.demo.jason.com/", className = "com.jason.demo.clientWSDL.Bye")
    @WebMethod
    @ResponseWrapper(localName = "byeResponse", targetNamespace = "http://service.demo.jason.com/", className = "com.jason.demo.clientWSDL.ByeResponse")
    public java.lang.String bye();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://service.demo.jason.com/", className = "com.jason.demo.clientWSDL.Hello")
    @WebMethod
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://service.demo.jason.com/", className = "com.jason.demo.clientWSDL.HelloResponse")
    public java.lang.String hello();

    @WebResult(name = "loginUser", targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://service.demo.jason.com/", className = "com.jason.demo.clientWSDL.Login")
    @WebMethod
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://service.demo.jason.com/", className = "com.jason.demo.clientWSDL.LoginResponse")
    public com.jason.demo.clientWSDL.User login(
        @WebParam(name = "username", targetNamespace = "")
        java.lang.String username,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password
    );
}
