
package com.jason.demo.clientWSDL;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-04-12T16:38:10.700+08:00
 * Generated source version: 2.7.18
 * 
 */
public final class IHelloService_HelloServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.service.demo.jason.com/", "JasonCaiHello");

    private IHelloService_HelloServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = JasonCaiHello.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        JasonCaiHello ss = new JasonCaiHello(wsdlURL, SERVICE_NAME);
        IHelloService port = ss.getHelloServiceImplPort();  
        
        {
        System.out.println("Invoking bye...");
        java.lang.String _bye__return = port.bye();
        System.out.println("bye.result=" + _bye__return);


        }
        {
        System.out.println("Invoking hello...");
        java.lang.String _hello__return = port.hello();
        System.out.println("hello.result=" + _hello__return);


        }
        {
        System.out.println("Invoking login...");
        java.lang.String _login_username = "";
        java.lang.String _login_password = "";
        com.jason.demo.clientWSDL.User _login__return = port.login(_login_username, _login_password);
        System.out.println("login.result=" + _login__return);


        }

        System.exit(0);
    }

}
