package com.jason.demo.clientWSDL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-04-12T16:38:10.752+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "JasonCaiHello", 
                  wsdlLocation = "file:/F:/My_Training/WebService/demo4_cxf_webserivce/src/com/jason/demo/clientWSDL/jason.wsdl",
                  targetNamespace = "http://impl.service.demo.jason.com/") 
public class JasonCaiHello extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.service.demo.jason.com/", "JasonCaiHello");
    public final static QName HelloServiceImplPort = new QName("http://impl.service.demo.jason.com/", "HelloServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/F:/My_Training/WebService/demo4_cxf_webserivce/src/com/jason/demo/clientWSDL/jason.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(JasonCaiHello.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/F:/My_Training/WebService/demo4_cxf_webserivce/src/com/jason/demo/clientWSDL/jason.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public JasonCaiHello(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public JasonCaiHello(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JasonCaiHello() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public JasonCaiHello(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public JasonCaiHello(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public JasonCaiHello(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IHelloService
     */
    @WebEndpoint(name = "HelloServiceImplPort")
    public IHelloService getHelloServiceImplPort() {
        return super.getPort(HelloServiceImplPort, IHelloService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IHelloService
     */
    @WebEndpoint(name = "HelloServiceImplPort")
    public IHelloService getHelloServiceImplPort(WebServiceFeature... features) {
        return super.getPort(HelloServiceImplPort, IHelloService.class, features);
    }

}
